In [1]:
import numpy as np

a = np.random.rand(5)

In [2]:
print(a)

[0.10259629 0.38683247 0.71768344 0.33542933 0.73391727]


In [4]:
print(a.shape) //(5,) is not a row vector or column vector

(5,)


In [5]:
print(a.T)

[0.10259629 0.38683247 0.71768344 0.33542933 0.73391727]


In [6]:
print(np.dot(a,a.T))

1.3263822688713622


## Recommended way

In [11]:
a = np.random.rand(5,1)
print(a)

[[0.03023063]
 [0.43944769]
 [0.4119984 ]
 [0.0695002 ]
 [0.7984947 ]]


In [12]:
print(a.T)

[[0.03023063 0.43944769 0.4119984  0.0695002  0.7984947 ]]


In [13]:
print(np.dot(a,a.T))

[[0.00091389 0.01328478 0.01245497 0.00210104 0.024139  ]
 [0.01328478 0.19311428 0.18105175 0.0305417  0.35089666]
 [0.01245497 0.18105175 0.16974268 0.02863397 0.32897854]
 [0.00210104 0.0305417  0.02863397 0.00483028 0.05549554]
 [0.024139   0.35089666 0.32897854 0.05549554 0.63759379]]
